// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbVersion() {
  return window['go']['main']['App']['AdbVersion']();
}

export function ConnectDevice(arg1) {
  return window['go']['main']['App']['ConnectDevice'](arg1);
}

export function DisconnectDevice(arg1) {
  return window['go']['main']['App']['DisconnectDevice'](arg1);
}

export function GetAdbPath() {
  return window['go']['main']['App']['GetAdbPath']();
}

export function GetConnectedDevices() {
  return window['go']['main']['App']['GetConnectedDevices']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function Noop(arg1) {
  return window['go']['main']['App']['Noop'](arg1);
}

export function PairDevice(arg1, arg2) {
  return window['go']['main']['App']['PairDevice'](arg1, arg2);
}

export function PickAdbPath() {
  return window['go']['main']['App']['PickAdbPath']();
}

export function RefreshKnownDevices() {
  return window['go']['main']['App']['RefreshKnownDevices']();
}

export function RestartServicesSearch() {
  return window['go']['main']['App']['RestartServicesSearch']();
}

export function SetAdbPath(arg1) {
  return window['go']['main']['App']['SetAdbPath'](arg1);
}
