// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';
import {zeroconf} from '../models';
import {netip} from '../models';

export function AdbVersion():Promise<string>;

export function ConnectDevice(arg1:string):Promise<string>;

export function DisconnectDevice(arg1:string):Promise<string>;

export function GetAdbPath():Promise<string>;

export function GetConnectedDevices():Promise<Array<adb.Device>>;

export function GetServices():Promise<Array<zeroconf.Service>>;

export function Noop(arg1:netip.Addr):Promise<void>;

export function PairDevice(arg1:string,arg2:string):Promise<string>;

export function PickAdbPath():Promise<string>;

export function RefreshKnownDevices():Promise<void>;

export function RestartServicesSearch():Promise<void>;

export function SetAdbPath(arg1:string):Promise<void>;
